Update to TSO500 for new Pipeline
AWGL/TSO500_post_processing pull request #56
Opened 2023-04-25 15:40 UTC by SophieS9

- Edits to the script to separate out the DNA and RNA analysis. 
- RNA continues as before.
- DNA now submits a bash script which kicks off the somatic_enrichment_nextflow pipeline. 
- Edits also made the to filter_sample.py script so that the referrals for DNA are all lower case.

2023-07-19 14:55 UTC, erikwaskiewicz requested changes
- See comments in code
- Version will now be 1.0.13 
- Change pipeline version from `sophie_update` before deploying, on `*_TSO500.sh` scripts and nextflow script kicked off on line 155

2023-07-19 14:55 UTC, erikwaskiewicz commented on 1_TSO500.sh
> +    cp -r ../Demultiplex_Output/Logs_Intermediates/FastqGeneration/${sampleID}/ ./Raw_Reads
Can we remove this line and run the cat command on next couple of lines directly from the original location?

2023-07-19 14:55 UTC, erikwaskiewicz commented on 1_TSO500.sh
> +done < samples_correct_order_*_DNA.csv
Have you tested with multiple DNA worksheets? This will work fine but just wandering if the nextflow downstream will be able to handle having the two different NTCs? The S2 run from the original validation had two DNA worksheets

2023-07-19 14:55 UTC, erikwaskiewicz commented on scripts/filter_sample_list.py
> +		line = line.split(",")
Can we have the tuple unpacking on this like the other scripts? so line[0] etc have variable names

2023-07-19 14:55 UTC, erikwaskiewicz commented on scripts/filter_sample_list.py
> +SAMPLESHEET = open('SampleSheet_updated.csv','r')
Can these be lowercase?

2023-07-19 14:57 UTC, erikwaskiewicz commented
Can you fix the conflicts too please? They're just in the header of the three *_TSO500.sh scripts

2023-07-26 11:34 UTC, SophieS9 commented
Code review changes all done and tested. All working. 

As per comment, doesn't currently work with multiple worksheets, but added as an issue and can change later. https://github.com/AWGL/TSO500_post_processing/issues/63

2023-08-01 13:14 UTC, erikwaskiewicz approved these changes
Changes look good, will hold here before merging into dev until we're ready for go live

2023-08-29 16:00 UTC, erikwaskiewicz commented
Happy with changes from latest commit, still holding until go live

2023-09-20 12:10 UTC, merged